version: '3.2'
services:
    php:
        image: ${COMPOSE_PROJECT_NAME:-project}_php:${TAG:-latest}
        build:
            context: .
            dockerfile: docker/services/php/Dockerfile

        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            CACHE_DRIVER: redis
            QUEUE_DRIVER: redis
            SESSION_DRIVER: redis
            REDIS_HOST: redis
            APP_LOG: syslog
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            APP_DEBUG: ${APP_DEBUG}
            APP_ENV: ${APP_ENV}


    nginx:
        image: ${COMPOSE_PROJECT_NAME:-project}_nginx:${TAG:-latest}
        build:
            context: .
            dockerfile: docker/services/nginx/Dockerfile
        ports:
            - ${WEB_PORT:-80}:80

    redis:
        image: redis

    mysql:
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-${DB_PASSWORD}}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
    mysql_data:

secrets:
    app_key:
        external: true
