version: '3.2'
services:
    php:
        image: ${COMPOSE_PROJECT_NAME:-project}_php
        build:
            context: .
            dockerfile: docker/services/php/Dockerfile
        deploy:
            replicas: 5
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
            CACHE_DRIVER: redis
            QUEUE_DRIVER: redis
            SESSION_DRIVER: redis
            REDIS_HOST: redis
            APP_LOG: syslog
            APP_DEBUG: ${APP_DEBUG}
            APP_ENV: ${APP_ENV}
        secrets:
            - app_key

    nginx:
        image: ${COMPOSE_PROJECT_NAME:-project}_nginx
        build:
            context: .
            dockerfile: docker/services/nginx/Dockerfile
        ports:
            - 9080:80

    redis:
        image: redis

    mysql:
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret

volumes:
    mysql_data:

secrets:
    app_key:
        external: true